<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateTownsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('towns', function (Blueprint $table) {
            $table->integer('id')->autoIncrement();
            $table->string('name');
            $table->tinyInteger('state');
            $table->integer('department_id');
            $table->foreign('department_id')->references('id')->on('departments');
            $table->timestamps();
        });

        DB::table('towns')->insert([
            ['name' => 'Acandí', 'state' => 1, 'department_id' => 27], ['name' => 'Acevedo', 'state' => 1, 'department_id' => 41],
            ['name' => 'Achí', 'state' => 1, 'department_id' => 13], ['name' => 'Agrado', 'state' => 1, 'department_id' => 41],
            ['name' => 'Agua de Dios', 'state' => 1, 'department_id' => 25], ['name' => 'Aguachica', 'state' => 1, 'department_id' => 20],
            ['name' => 'Aguada', 'state' => 1, 'department_id' => 68], ['name' => 'Aguadas', 'state' => 1, 'department_id' => 17],
            ['name' => 'Aguazul', 'state' => 1, 'department_id' => 85], ['name' => 'Agustín Codazzi', 'state' => 1, 'department_id' => 20],
            ['name' => 'Aipe', 'state' => 1, 'department_id' => 41], ['name' => 'Albania', 'state' => 1, 'department_id' => 18],
            ['name' => 'Albania', 'state' => 1, 'department_id' => 44], ['name' => 'Albania', 'state' => 1, 'department_id' => 68],
            ['name' => 'Albán', 'state' => 1, 'department_id' => 25], ['name' => 'Albán (San José)', 'state' => 1, 'department_id' => 52],
            ['name' => 'Alcalá', 'state' => 1, 'department_id' => 76], ['name' => 'Alejandria', 'state' => 1, 'department_id' => 5],
            ['name' => 'Algarrobo', 'state' => 1, 'department_id' => 47], ['name' => 'Algeciras', 'state' => 1, 'department_id' => 41],
            ['name' => 'Almaguer', 'state' => 1, 'department_id' => 19], ['name' => 'Almeida', 'state' => 1, 'department_id' => 15],
            ['name' => 'Alpujarra', 'state' => 1, 'department_id' => 73], ['name' => 'Altamira', 'state' => 1, 'department_id' => 41],
            ['name' => 'Alto Baudó (Pie de Pato)', 'state' => 1, 'department_id' => 27], ['name' => 'Altos del Rosario', 'state' => 1, 'department_id' => 13],
            ['name' => 'Alvarado', 'state' => 1, 'department_id' => 73], ['name' => 'Amagá', 'state' => 1, 'department_id' => 5],
            ['name' => 'Amalfi', 'state' => 1, 'department_id' => 5], ['name' => 'Ambalema', 'state' => 1, 'department_id' => 73],
            ['name' => 'Anapoima', 'state' => 1, 'department_id' => 25], ['name' => 'Ancuya', 'state' => 1, 'department_id' => 52],
            ['name' => 'Andalucía', 'state' => 1, 'department_id' => 76], ['name' => 'Andes', 'state' => 1, 'department_id' => 5],
            ['name' => 'Angelópolis', 'state' => 1, 'department_id' => 5], ['name' => 'Angostura', 'state' => 1, 'department_id' => 5],
            ['name' => 'Anolaima', 'state' => 1, 'department_id' => 25], ['name' => 'Anorí', 'state' => 1, 'department_id' => 5],
            ['name' => 'Anserma', 'state' => 1, 'department_id' => 17], ['name' => 'Ansermanuevo', 'state' => 1, 'department_id' => 76],
            ['name' => 'Anzoátegui', 'state' => 1, 'department_id' => 73], ['name' => 'Anzá', 'state' => 1, 'department_id' => 5],
            ['name' => 'Apartadó', 'state' => 1, 'department_id' => 5], ['name' => 'Apulo', 'state' => 1, 'department_id' => 25],
            ['name' => 'Apía', 'state' => 1, 'department_id' => 66], ['name' => 'Aquitania', 'state' => 1, 'department_id' => 15],
            ['name' => 'Aracataca', 'state' => 1, 'department_id' => 47], ['name' => 'Aranzazu', 'state' => 1, 'department_id' => 17],
            ['name' => 'Aratoca', 'state' => 1, 'department_id' => 68], ['name' => 'Arauca', 'state' => 1, 'department_id' => 81],
            ['name' => 'Arauquita', 'state' => 1, 'department_id' => 81], ['name' => 'Arbeláez', 'state' => 1, 'department_id' => 25],
            ['name' => 'Arboleda (Berruecos)', 'state' => 1, 'department_id' => 52], ['name' => 'Arboledas', 'state' => 1, 'department_id' => 54],
            ['name' => 'Arboletes', 'state' => 1, 'department_id' => 5], ['name' => 'Arcabuco', 'state' => 1, 'department_id' => 15],
            ['name' => 'Arenal', 'state' => 1, 'department_id' => 13], ['name' => 'Argelia', 'state' => 1, 'department_id' => 5],
            ['name' => 'Argelia', 'state' => 1, 'department_id' => 19], ['name' => 'Argelia', 'state' => 1, 'department_id' => 76],
            ['name' => 'Ariguaní (El Difícil)', 'state' => 1, 'department_id' => 47], ['name' => 'Arjona', 'state' => 1, 'department_id' => 13],
            ['name' => 'Armenia', 'state' => 1, 'department_id' => 5], ['name' => 'Armenia', 'state' => 1, 'department_id' => 63],
            ['name' => 'Armero (Guayabal)', 'state' => 1, 'department_id' => 73], ['name' => 'Arroyohondo', 'state' => 1, 'department_id' => 13],
            ['name' => 'Astrea', 'state' => 1, 'department_id' => 20], ['name' => 'Ataco', 'state' => 1, 'department_id' => 73],
            ['name' => 'Atrato (Yuto)', 'state' => 1, 'department_id' => 27], ['name' => 'Ayapel', 'state' => 1, 'department_id' => 23],
            ['name' => 'Bagadó', 'state' => 1, 'department_id' => 27], ['name' => 'Bahía Solano (Mútis)', 'state' => 1, 'department_id' => 27],
            ['name' => 'Bajo Baudó (Pizarro)', 'state' => 1, 'department_id' => 27], ['name' => 'Balboa', 'state' => 1, 'department_id' => 19],
            ['name' => 'Balboa', 'state' => 1, 'department_id' => 66], ['name' => 'Baranoa', 'state' => 1, 'department_id' => 8],
            ['name' => 'Baraya', 'state' => 1, 'department_id' => 41], ['name' => 'Barbacoas', 'state' => 1, 'department_id' => 52],
            ['name' => 'Barbosa', 'state' => 1, 'department_id' => 5], ['name' => 'Barbosa', 'state' => 1, 'department_id' => 68],
            ['name' => 'Barichara', 'state' => 1, 'department_id' => 68], ['name' => 'Barranca de Upía', 'state' => 1, 'department_id' => 50],
            ['name' => 'Barrancabermeja', 'state' => 1, 'department_id' => 68], ['name' => 'Barrancas', 'state' => 1, 'department_id' => 44],
            ['name' => 'Barranco de Loba', 'state' => 1, 'department_id' => 13], ['name' => 'Barranquilla', 'state' => 1, 'department_id' => 8],
            ['name' => 'Becerríl', 'state' => 1, 'department_id' => 20], ['name' => 'Belalcázar', 'state' => 1, 'department_id' => 17],
            ['name' => 'Bello', 'state' => 1, 'department_id' => 5], ['name' => 'Belmira', 'state' => 1, 'department_id' => 5],
            ['name' => 'Beltrán', 'state' => 1, 'department_id' => 25], ['name' => 'Belén', 'state' => 1, 'department_id' => 15],
            ['name' => 'Belén', 'state' => 1, 'department_id' => 52], ['name' => 'Belén de Bajirá', 'state' => 1, 'department_id' => 27],
            ['name' => 'Belén de Umbría', 'state' => 1, 'department_id' => 66], ['name' => 'Belén de los Andaquíes', 'state' => 1, 'department_id' => 18],
            ['name' => 'Berbeo', 'state' => 1, 'department_id' => 15], ['name' => 'Betania', 'state' => 1, 'department_id' => 5],
            ['name' => 'Beteitiva', 'state' => 1, 'department_id' => 15], ['name' => 'Betulia', 'state' => 1, 'department_id' => 5],
            ['name' => 'Betulia', 'state' => 1, 'department_id' => 68], ['name' => 'Bituima', 'state' => 1, 'department_id' => 25],
            ['name' => 'Boavita', 'state' => 1, 'department_id' => 15], ['name' => 'Bochalema', 'state' => 1, 'department_id' => 54],
            ['name' => 'Bogotá D.C.', 'state' => 1, 'department_id' => 11], ['name' => 'Bojacá', 'state' => 1, 'department_id' => 25],
            ['name' => 'Bojayá (Bellavista)', 'state' => 1, 'department_id' => 27], ['name' => 'Bolívar', 'state' => 1, 'department_id' => 5],
            ['name' => 'Bolívar', 'state' => 1, 'department_id' => 19], ['name' => 'Bolívar', 'state' => 1, 'department_id' => 68],
            ['name' => 'Bolívar', 'state' => 1, 'department_id' => 76], ['name' => 'Bosconia', 'state' => 1, 'department_id' => 20],
            ['name' => 'Boyacá', 'state' => 1, 'department_id' => 15], ['name' => 'Briceño', 'state' => 1, 'department_id' => 5],
            ['name' => 'Briceño', 'state' => 1, 'department_id' => 15], ['name' => 'Bucaramanga', 'state' => 1, 'department_id' => 68],
            ['name' => 'Bucarasica', 'state' => 1, 'department_id' => 54], ['name' => 'Buenaventura', 'state' => 1, 'department_id' => 76],
            ['name' => 'Buenavista', 'state' => 1, 'department_id' => 15], ['name' => 'Buenavista', 'state' => 1, 'department_id' => 23],
            ['name' => 'Buenavista', 'state' => 1, 'department_id' => 63], ['name' => 'Buenavista', 'state' => 1, 'department_id' => 70],
            ['name' => 'Buenos Aires', 'state' => 1, 'department_id' => 19],
            ['name' => 'Buesaco', 'state' => 1, 'department_id' => 52],
            ['name' => 'Buga', 'state' => 1, 'department_id' => 76],
            ['name' => 'Bugalagrande', 'state' => 1, 'department_id' => 76],
            ['name' => 'Burítica', 'state' => 1, 'department_id' => 5],
            ['name' => 'Busbanza', 'state' => 1, 'department_id' => 15],
            ['name' => 'Cabrera', 'state' => 1, 'department_id' => 25],
            ['name' => 'Cabrera', 'state' => 1, 'department_id' => 68],
            ['name' => 'Cabuyaro', 'state' => 1, 'department_id' => 50],
            ['name' => 'Cachipay', 'state' => 1, 'department_id' => 25],
            ['name' => 'Caicedo', 'state' => 1, 'department_id' => 5],
            ['name' => 'Caicedonia', 'state' => 1, 'department_id' => 76],
            ['name' => 'Caimito', 'state' => 1, 'department_id' => 70],
            ['name' => 'Cajamarca', 'state' => 1, 'department_id' => 73],
            ['name' => 'Cajibío', 'state' => 1, 'department_id' => 19],
            ['name' => 'Cajicá', 'state' => 1, 'department_id' => 25],
            ['name' => 'Calamar', 'state' => 1, 'department_id' => 13],
            ['name' => 'Calamar', 'state' => 1, 'department_id' => 95],
            ['name' => 'Calarcá', 'state' => 1, 'department_id' => 63],
            ['name' => 'Caldas', 'state' => 1, 'department_id' => 5],
            ['name' => 'Caldas', 'state' => 1, 'department_id' => 15],
            ['name' => 'Caldono', 'state' => 1, 'department_id' => 19],
            ['name' => 'California', 'state' => 1, 'department_id' => 68],
            ['name' => 'Calima (Darién)', 'state' => 1, 'department_id' => 76],
            ['name' => 'Caloto', 'state' => 1, 'department_id' => 19],
            ['name' => 'Calí', 'state' => 1, 'department_id' => 76],
            ['name' => 'Campamento', 'state' => 1, 'department_id' => 5],
            ['name' => 'Campo de la Cruz', 'state' => 1, 'department_id' => 8],
            ['name' => 'Campoalegre', 'state' => 1, 'department_id' => 41],
            ['name' => 'Campohermoso', 'state' => 1, 'department_id' => 15],
            ['name' => 'Canalete', 'state' => 1, 'department_id' => 23],
            ['name' => 'Candelaria', 'state' => 1, 'department_id' => 8],
            ['name' => 'Candelaria', 'state' => 1, 'department_id' => 76],
            ['name' => 'Cantagallo', 'state' => 1, 'department_id' => 13],
            ['name' => 'Cantón de San Pablo', 'state' => 1, 'department_id' => 27],
            ['name' => 'Caparrapí', 'state' => 1, 'department_id' => 25],
            ['name' => 'Capitanejo', 'state' => 1, 'department_id' => 68],
            ['name' => 'Caracolí', 'state' => 1, 'department_id' => 5],
            ['name' => 'Caramanta', 'state' => 1, 'department_id' => 5],
            ['name' => 'Carcasí', 'state' => 1, 'department_id' => 68],
            ['name' => 'Carepa', 'state' => 1, 'department_id' => 5],
            ['name' => 'Carmen de Apicalá', 'state' => 1, 'department_id' => 73],
            ['name' => 'Carmen de Carupa', 'state' => 1, 'department_id' => 25],
            ['name' => 'Carmen de Viboral', 'state' => 1, 'department_id' => 5],
            ['name' => 'Carmen del Darién (CURBARADÓ)', 'state' => 1, 'department_id' => 27],
            ['name' => 'Carolina', 'state' => 1, 'department_id' => 5],
            ['name' => 'Cartagena', 'state' => 1, 'department_id' => 13],
            ['name' => 'Cartagena del Chairá', 'state' => 1, 'department_id' => 18],
            ['name' => 'Cartago', 'state' => 1, 'department_id' => 76],
            ['name' => 'Carurú', 'state' => 1, 'department_id' => 97],
            ['name' => 'Casabianca', 'state' => 1, 'department_id' => 73],
            ['name' => 'Castilla la Nueva', 'state' => 1, 'department_id' => 50],
            ['name' => 'Caucasia', 'state' => 1, 'department_id' => 5],
            ['name' => 'Cañasgordas', 'state' => 1, 'department_id' => 5],
            ['name' => 'Cepita', 'state' => 1, 'department_id' => 68],
            ['name' => 'Cereté', 'state' => 1, 'department_id' => 23],
            ['name' => 'Cerinza', 'state' => 1, 'department_id' => 15],
            ['name' => 'Cerrito', 'state' => 1, 'department_id' => 68],
            ['name' => 'Cerro San Antonio', 'state' => 1, 'department_id' => 47],
            ['name' => 'Chachaguí', 'state' => 1, 'department_id' => 52],
            ['name' => 'Chaguaní', 'state' => 1, 'department_id' => 25],
            ['name' => 'Chalán', 'state' => 1, 'department_id' => 70],
            ['name' => 'Chaparral', 'state' => 1, 'department_id' => 73],
            ['name' => 'Charalá', 'state' => 1, 'department_id' => 68],
            ['name' => 'Charta', 'state' => 1, 'department_id' => 68],
            ['name' => 'Chigorodó', 'state' => 1, 'department_id' => 5],
            ['name' => 'Chima', 'state' => 1, 'department_id' => 68],
            ['name' => 'Chimichagua', 'state' => 1, 'department_id' => 20],
            ['name' => 'Chimá', 'state' => 1, 'department_id' => 23],
            ['name' => 'Chinavita', 'state' => 1, 'department_id' => 15],
            ['name' => 'Chinchiná', 'state' => 1, 'department_id' => 17],
            ['name' => 'Chinácota', 'state' => 1, 'department_id' => 54],
            ['name' => 'Chinú', 'state' => 1, 'department_id' => 23],
            ['name' => 'Chipaque', 'state' => 1, 'department_id' => 25],
            ['name' => 'Chipatá', 'state' => 1, 'department_id' => 68],
            ['name' => 'Chiquinquirá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Chiriguaná', 'state' => 1, 'department_id' => 20],
            ['name' => 'Chiscas', 'state' => 1, 'department_id' => 15],
            ['name' => 'Chita', 'state' => 1, 'department_id' => 15],
            ['name' => 'Chitagá', 'state' => 1, 'department_id' => 54],
            ['name' => 'Chitaraque', 'state' => 1, 'department_id' => 15],
            ['name' => 'Chivatá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Chivolo', 'state' => 1, 'department_id' => 47],
            ['name' => 'Choachí', 'state' => 1, 'department_id' => 25],
            ['name' => 'Chocontá', 'state' => 1, 'department_id' => 25],
            ['name' => 'Chámeza', 'state' => 1, 'department_id' => 85],
            ['name' => 'Chía', 'state' => 1, 'department_id' => 25],
            ['name' => 'Chíquiza', 'state' => 1, 'department_id' => 15],
            ['name' => 'Chívor', 'state' => 1, 'department_id' => 15],
            ['name' => 'Cicuco', 'state' => 1, 'department_id' => 13],
            ['name' => 'Cimitarra', 'state' => 1, 'department_id' => 68],
            ['name' => 'Circasia', 'state' => 1, 'department_id' => 63],
            ['name' => 'Cisneros', 'state' => 1, 'department_id' => 5],
            ['name' => 'Ciénaga', 'state' => 1, 'department_id' => 15],
            ['name' => 'Ciénaga', 'state' => 1, 'department_id' => 47],
            ['name' => 'Ciénaga de Oro', 'state' => 1, 'department_id' => 23],
            ['name' => 'Clemencia', 'state' => 1, 'department_id' => 13],
            ['name' => 'Cocorná', 'state' => 1, 'department_id' => 5],
            ['name' => 'Coello', 'state' => 1, 'department_id' => 73],
            ['name' => 'Cogua', 'state' => 1, 'department_id' => 25],
            ['name' => 'Colombia', 'state' => 1, 'department_id' => 41],
            ['name' => 'Colosó (Ricaurte)', 'state' => 1, 'department_id' => 70],
            ['name' => 'Colón', 'state' => 1, 'department_id' => 86],
            ['name' => 'Colón (Génova)', 'state' => 1, 'department_id' => 52],
            ['name' => 'Concepción', 'state' => 1, 'department_id' => 5],
            ['name' => 'Concepción', 'state' => 1, 'department_id' => 68],
            ['name' => 'Concordia', 'state' => 1, 'department_id' => 5],
            ['name' => 'Concordia', 'state' => 1, 'department_id' => 47],
            ['name' => 'Condoto', 'state' => 1, 'department_id' => 27],
            ['name' => 'Confines', 'state' => 1, 'department_id' => 68],
            ['name' => 'Consaca', 'state' => 1, 'department_id' => 52],
            ['name' => 'Contadero', 'state' => 1, 'department_id' => 52],
            ['name' => 'Contratación', 'state' => 1, 'department_id' => 68],
            ['name' => 'Convención', 'state' => 1, 'department_id' => 54],
            ['name' => 'Copacabana', 'state' => 1, 'department_id' => 5],
            ['name' => 'Coper', 'state' => 1, 'department_id' => 15],
            ['name' => 'Cordobá', 'state' => 1, 'department_id' => 63],
            ['name' => 'Corinto', 'state' => 1, 'department_id' => 19],
            ['name' => 'Coromoro', 'state' => 1, 'department_id' => 68],
            ['name' => 'Corozal', 'state' => 1, 'department_id' => 70],
            ['name' => 'Corrales', 'state' => 1, 'department_id' => 15],
            ['name' => 'Cota', 'state' => 1, 'department_id' => 25],
            ['name' => 'Cotorra', 'state' => 1, 'department_id' => 23],
            ['name' => 'Covarachía', 'state' => 1, 'department_id' => 15],
            ['name' => 'Coveñas', 'state' => 1, 'department_id' => 70],
            ['name' => 'Coyaima', 'state' => 1, 'department_id' => 73],
            ['name' => 'Cravo Norte', 'state' => 1, 'department_id' => 81],
            ['name' => 'Cuaspud (Carlosama)', 'state' => 1, 'department_id' => 52],
            ['name' => 'Cubarral', 'state' => 1, 'department_id' => 50],
            ['name' => 'Cubará', 'state' => 1, 'department_id' => 15],
            ['name' => 'Cucaita', 'state' => 1, 'department_id' => 15],
            ['name' => 'Cucunubá', 'state' => 1, 'department_id' => 25],
            ['name' => 'Cucutilla', 'state' => 1, 'department_id' => 54],
            ['name' => 'Cuitiva', 'state' => 1, 'department_id' => 15],
            ['name' => 'Cumaral', 'state' => 1, 'department_id' => 50],
            ['name' => 'Cumaribo', 'state' => 1, 'department_id' => 99],
            ['name' => 'Cumbal', 'state' => 1, 'department_id' => 52],
            ['name' => 'Cumbitara', 'state' => 1, 'department_id' => 52],
            ['name' => 'Cunday', 'state' => 1, 'department_id' => 73],
            ['name' => 'Curillo', 'state' => 1, 'department_id' => 18],
            ['name' => 'Curití', 'state' => 1, 'department_id' => 68],
            ['name' => 'Curumaní', 'state' => 1, 'department_id' => 20],
            ['name' => 'Cáceres', 'state' => 1, 'department_id' => 5],
            ['name' => 'Cáchira', 'state' => 1, 'department_id' => 54],
            ['name' => 'Cácota', 'state' => 1, 'department_id' => 54],
            ['name' => 'Cáqueza', 'state' => 1, 'department_id' => 25],
            ['name' => 'Cértegui', 'state' => 1, 'department_id' => 27],
            ['name' => 'Cómbita', 'state' => 1, 'department_id' => 15],
            ['name' => 'Córdoba', 'state' => 1, 'department_id' => 13],
            ['name' => 'Córdoba', 'state' => 1, 'department_id' => 52],
            ['name' => 'Cúcuta', 'state' => 1, 'department_id' => 54],
            ['name' => 'Dabeiba', 'state' => 1, 'department_id' => 5],
            ['name' => 'Dagua', 'state' => 1, 'department_id' => 76],
            ['name' => 'Dibulla', 'state' => 1, 'department_id' => 44],
            ['name' => 'Distracción', 'state' => 1, 'department_id' => 44],
            ['name' => 'Dolores', 'state' => 1, 'department_id' => 73],
            ['name' => 'Don Matías', 'state' => 1, 'department_id' => 5],
            ['name' => 'Dos Quebradas', 'state' => 1, 'department_id' => 66],
            ['name' => 'Duitama', 'state' => 1, 'department_id' => 15],
            ['name' => 'Durania', 'state' => 1, 'department_id' => 54],
            ['name' => 'Ebéjico', 'state' => 1, 'department_id' => 5],
            ['name' => 'El Bagre', 'state' => 1, 'department_id' => 5],
            ['name' => 'El Banco', 'state' => 1, 'department_id' => 47],
            ['name' => 'El Cairo', 'state' => 1, 'department_id' => 76],
            ['name' => 'El Calvario', 'state' => 1, 'department_id' => 50],
            ['name' => 'El Carmen', 'state' => 1, 'department_id' => 54],
            ['name' => 'El Carmen', 'state' => 1, 'department_id' => 68],
            ['name' => 'El Carmen de Atrato', 'state' => 1, 'department_id' => 27],
            ['name' => 'El Carmen de Bolívar', 'state' => 1, 'department_id' => 13],
            ['name' => 'El Castillo', 'state' => 1, 'department_id' => 50],
            ['name' => 'El Cerrito', 'state' => 1, 'department_id' => 76],
            ['name' => 'El Charco', 'state' => 1, 'department_id' => 52],
            ['name' => 'El Cocuy', 'state' => 1, 'department_id' => 15],
            ['name' => 'El Colegio', 'state' => 1, 'department_id' => 25],
            ['name' => 'El Copey', 'state' => 1, 'department_id' => 20],
            ['name' => 'El Doncello', 'state' => 1, 'department_id' => 18],
            ['name' => 'El Dorado', 'state' => 1, 'department_id' => 50],
            ['name' => 'El Dovio', 'state' => 1, 'department_id' => 76],
            ['name' => 'El Espino', 'state' => 1, 'department_id' => 15],
            ['name' => 'El Guacamayo', 'state' => 1, 'department_id' => 68],
            ['name' => 'El Guamo', 'state' => 1, 'department_id' => 13],
            ['name' => 'El Molino', 'state' => 1, 'department_id' => 44],
            ['name' => 'El Paso', 'state' => 1, 'department_id' => 20],
            ['name' => 'El Paujil', 'state' => 1, 'department_id' => 18],
            ['name' => 'El Peñol', 'state' => 1, 'department_id' => 52],
            ['name' => 'El Peñon', 'state' => 1, 'department_id' => 13],
            ['name' => 'El Peñon', 'state' => 1, 'department_id' => 68],
            ['name' => 'El Peñón', 'state' => 1, 'department_id' => 25],
            ['name' => 'El Piñon', 'state' => 1, 'department_id' => 47],
            ['name' => 'El Playón', 'state' => 1, 'department_id' => 68],
            ['name' => 'El Retorno', 'state' => 1, 'department_id' => 95],
            ['name' => 'El Retén', 'state' => 1, 'department_id' => 47],
            ['name' => 'El Roble', 'state' => 1, 'department_id' => 70],
            ['name' => 'El Rosal', 'state' => 1, 'department_id' => 25],
            ['name' => 'El Rosario', 'state' => 1, 'department_id' => 52],
            ['name' => 'El Tablón de Gómez', 'state' => 1, 'department_id' => 52],
            ['name' => 'El Tambo', 'state' => 1, 'department_id' => 19],
            ['name' => 'El Tambo', 'state' => 1, 'department_id' => 52],
            ['name' => 'El Tarra', 'state' => 1, 'department_id' => 54],
            ['name' => 'El Zulia', 'state' => 1, 'department_id' => 54],
            ['name' => 'El Águila', 'state' => 1, 'department_id' => 76],
            ['name' => 'Elías', 'state' => 1, 'department_id' => 41],
            ['name' => 'Encino', 'state' => 1, 'department_id' => 68],
            ['name' => 'Enciso', 'state' => 1, 'department_id' => 68],
            ['name' => 'Entrerríos', 'state' => 1, 'department_id' => 5],
            ['name' => 'Envigado', 'state' => 1, 'department_id' => 5],
            ['name' => 'Espinal', 'state' => 1, 'department_id' => 73],
            ['name' => 'Facatativá', 'state' => 1, 'department_id' => 25],
            ['name' => 'Falan', 'state' => 1, 'department_id' => 73],
            ['name' => 'Filadelfia', 'state' => 1, 'department_id' => 17],
            ['name' => 'Filandia', 'state' => 1, 'department_id' => 63],
            ['name' => 'Firavitoba', 'state' => 1, 'department_id' => 15],
            ['name' => 'Flandes', 'state' => 1, 'department_id' => 73],
            ['name' => 'Florencia', 'state' => 1, 'department_id' => 18],
            ['name' => 'Florencia', 'state' => 1, 'department_id' => 19],
            ['name' => 'Floresta', 'state' => 1, 'department_id' => 15],
            ['name' => 'Florida', 'state' => 1, 'department_id' => 76],
            ['name' => 'Floridablanca', 'state' => 1, 'department_id' => 68],
            ['name' => 'Florián', 'state' => 1, 'department_id' => 68],
            ['name' => 'Fonseca', 'state' => 1, 'department_id' => 44],
            ['name' => 'Fortúl', 'state' => 1, 'department_id' => 81],
            ['name' => 'Fosca', 'state' => 1, 'department_id' => 25],
            ['name' => 'Francisco Pizarro', 'state' => 1, 'department_id' => 52],
            ['name' => 'Fredonia', 'state' => 1, 'department_id' => 5],
            ['name' => 'Fresno', 'state' => 1, 'department_id' => 73],
            ['name' => 'Frontino', 'state' => 1, 'department_id' => 5],
            ['name' => 'Fuente de Oro', 'state' => 1, 'department_id' => 50],
            ['name' => 'Fundación', 'state' => 1, 'department_id' => 47],
            ['name' => 'Funes', 'state' => 1, 'department_id' => 52],
            ['name' => 'Funza', 'state' => 1, 'department_id' => 25],
            ['name' => 'Fusagasugá', 'state' => 1, 'department_id' => 25],
            ['name' => 'Fómeque', 'state' => 1, 'department_id' => 25],
            ['name' => 'Fúquene', 'state' => 1, 'department_id' => 25],
            ['name' => 'Gachalá', 'state' => 1, 'department_id' => 25],
            ['name' => 'Gachancipá', 'state' => 1, 'department_id' => 25],
            ['name' => 'Gachantivá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Gachetá', 'state' => 1, 'department_id' => 25],
            ['name' => 'Galapa', 'state' => 1, 'department_id' => 8],
            ['name' => 'Galeras (Nueva Granada)', 'state' => 1, 'department_id' => 70],
            ['name' => 'Galán', 'state' => 1, 'department_id' => 68],
            ['name' => 'Gama', 'state' => 1, 'department_id' => 25],
            ['name' => 'Gamarra', 'state' => 1, 'department_id' => 20],
            ['name' => 'Garagoa', 'state' => 1, 'department_id' => 15],
            ['name' => 'Garzón', 'state' => 1, 'department_id' => 41],
            ['name' => 'Gigante', 'state' => 1, 'department_id' => 41],
            ['name' => 'Ginebra', 'state' => 1, 'department_id' => 76],
            ['name' => 'Giraldo', 'state' => 1, 'department_id' => 5],
            ['name' => 'Girardot', 'state' => 1, 'department_id' => 25],
            ['name' => 'Girardota', 'state' => 1, 'department_id' => 5],
            ['name' => 'Girón', 'state' => 1, 'department_id' => 68],
            ['name' => 'Gonzalez', 'state' => 1, 'department_id' => 20],
            ['name' => 'Gramalote', 'state' => 1, 'department_id' => 54],
            ['name' => 'Granada', 'state' => 1, 'department_id' => 5],
            ['name' => 'Granada', 'state' => 1, 'department_id' => 25],
            ['name' => 'Granada', 'state' => 1, 'department_id' => 50],
            ['name' => 'Guaca', 'state' => 1, 'department_id' => 68],
            ['name' => 'Guacamayas', 'state' => 1, 'department_id' => 15],
            ['name' => 'Guacarí', 'state' => 1, 'department_id' => 76],
            ['name' => 'Guachavés', 'state' => 1, 'department_id' => 52],
            ['name' => 'Guachené', 'state' => 1, 'department_id' => 19],
            ['name' => 'Guachetá', 'state' => 1, 'department_id' => 25],
            ['name' => 'Guachucal', 'state' => 1, 'department_id' => 52],
            ['name' => 'Guadalupe', 'state' => 1, 'department_id' => 5],
            ['name' => 'Guadalupe', 'state' => 1, 'department_id' => 41],
            ['name' => 'Guadalupe', 'state' => 1, 'department_id' => 68],
            ['name' => 'Guaduas', 'state' => 1, 'department_id' => 25],
            ['name' => 'Guaitarilla', 'state' => 1, 'department_id' => 52],
            ['name' => 'Gualmatán', 'state' => 1, 'department_id' => 52],
            ['name' => 'Guamal', 'state' => 1, 'department_id' => 47],
            ['name' => 'Guamal', 'state' => 1, 'department_id' => 50],
            ['name' => 'Guamo', 'state' => 1, 'department_id' => 73],
            ['name' => 'Guapota', 'state' => 1, 'department_id' => 68],
            ['name' => 'Guapí', 'state' => 1, 'department_id' => 19],
            ['name' => 'Guaranda', 'state' => 1, 'department_id' => 70],
            ['name' => 'Guarne', 'state' => 1, 'department_id' => 5],
            ['name' => 'Guasca', 'state' => 1, 'department_id' => 25],
            ['name' => 'Guatapé', 'state' => 1, 'department_id' => 5],
            ['name' => 'Guataquí', 'state' => 1, 'department_id' => 25],
            ['name' => 'Guatavita', 'state' => 1, 'department_id' => 25],
            ['name' => 'Guateque', 'state' => 1, 'department_id' => 15],
            ['name' => 'Guavatá', 'state' => 1, 'department_id' => 68],
            ['name' => 'Guayabal de Siquima', 'state' => 1, 'department_id' => 25],
            ['name' => 'Guayabetal', 'state' => 1, 'department_id' => 25],
            ['name' => 'Guayatá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Guepsa', 'state' => 1, 'department_id' => 68],
            ['name' => 'Guicán', 'state' => 1, 'department_id' => 15],
            ['name' => 'Gutiérrez', 'state' => 1, 'department_id' => 25],
            ['name' => 'Guática', 'state' => 1, 'department_id' => 66],
            ['name' => 'Gámbita', 'state' => 1, 'department_id' => 68],
            ['name' => 'Gámeza', 'state' => 1, 'department_id' => 15],
            ['name' => 'Génova', 'state' => 1, 'department_id' => 63],
            ['name' => 'Gómez Plata', 'state' => 1, 'department_id' => 5],
            ['name' => 'Hacarí', 'state' => 1, 'department_id' => 54],
            ['name' => 'Hatillo de Loba', 'state' => 1, 'department_id' => 13],
            ['name' => 'Hato', 'state' => 1, 'department_id' => 68],
            ['name' => 'Hato Corozal', 'state' => 1, 'department_id' => 85],
            ['name' => 'Hatonuevo', 'state' => 1, 'department_id' => 44],
            ['name' => 'Heliconia', 'state' => 1, 'department_id' => 5],
            ['name' => 'Herrán', 'state' => 1, 'department_id' => 54],
            ['name' => 'Herveo', 'state' => 1, 'department_id' => 73],
            ['name' => 'Hispania', 'state' => 1, 'department_id' => 5],
            ['name' => 'Hobo', 'state' => 1, 'department_id' => 41],
            ['name' => 'Honda', 'state' => 1, 'department_id' => 73],
            ['name' => 'Ibagué', 'state' => 1, 'department_id' => 73],
            ['name' => 'Icononzo', 'state' => 1, 'department_id' => 73],
            ['name' => 'Iles', 'state' => 1, 'department_id' => 52],
            ['name' => 'Imúes', 'state' => 1, 'department_id' => 52],
            ['name' => 'Inzá', 'state' => 1, 'department_id' => 19],
            ['name' => 'Inírida', 'state' => 1, 'department_id' => 94],
            ['name' => 'Ipiales', 'state' => 1, 'department_id' => 52],
            ['name' => 'Isnos', 'state' => 1, 'department_id' => 41],
            ['name' => 'Istmina', 'state' => 1, 'department_id' => 27],
            ['name' => 'Itagüí', 'state' => 1, 'department_id' => 5],
            ['name' => 'Ituango', 'state' => 1, 'department_id' => 5],
            ['name' => 'Izá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Jambaló', 'state' => 1, 'department_id' => 19],
            ['name' => 'Jamundí', 'state' => 1, 'department_id' => 76],
            ['name' => 'Jardín', 'state' => 1, 'department_id' => 5],
            ['name' => 'Jenesano', 'state' => 1, 'department_id' => 15],
            ['name' => 'Jericó', 'state' => 1, 'department_id' => 5],
            ['name' => 'Jericó', 'state' => 1, 'department_id' => 15],
            ['name' => 'Jerusalén', 'state' => 1, 'department_id' => 25],
            ['name' => 'Jesús María', 'state' => 1, 'department_id' => 68],
            ['name' => 'Jordán', 'state' => 1, 'department_id' => 68],
            ['name' => 'Juan de Acosta', 'state' => 1, 'department_id' => 8],
            ['name' => 'Junín', 'state' => 1, 'department_id' => 25],
            ['name' => 'Juradó', 'state' => 1, 'department_id' => 27],
            ['name' => 'La Apartada y La Frontera', 'state' => 1, 'department_id' => 23],
            ['name' => 'La Argentina', 'state' => 1, 'department_id' => 41],
            ['name' => 'La Belleza', 'state' => 1, 'department_id' => 68],
            ['name' => 'La Calera', 'state' => 1, 'department_id' => 25],
            ['name' => 'La Capilla', 'state' => 1, 'department_id' => 15],
            ['name' => 'La Ceja', 'state' => 1, 'department_id' => 5],
            ['name' => 'La Celia', 'state' => 1, 'department_id' => 66],
            ['name' => 'La Cruz', 'state' => 1, 'department_id' => 52],
            ['name' => 'La Cumbre', 'state' => 1, 'department_id' => 76],
            ['name' => 'La Dorada', 'state' => 1, 'department_id' => 17],
            ['name' => 'La Esperanza', 'state' => 1, 'department_id' => 54],
            ['name' => 'La Estrella', 'state' => 1, 'department_id' => 5],
            ['name' => 'La Florida', 'state' => 1, 'department_id' => 52],
            ['name' => 'La Gloria', 'state' => 1, 'department_id' => 20],
            ['name' => 'La Jagua de Ibirico', 'state' => 1, 'department_id' => 20],
            ['name' => 'La Jagua del Pilar', 'state' => 1, 'department_id' => 44],
            ['name' => 'La Llanada', 'state' => 1, 'department_id' => 52],
            ['name' => 'La Macarena', 'state' => 1, 'department_id' => 50],
            ['name' => 'La Merced', 'state' => 1, 'department_id' => 17],
            ['name' => 'La Mesa', 'state' => 1, 'department_id' => 25],
            ['name' => 'La Montañita', 'state' => 1, 'department_id' => 18],
            ['name' => 'La Palma', 'state' => 1, 'department_id' => 25],
            ['name' => 'La Paz', 'state' => 1, 'department_id' => 68],
            ['name' => 'La Paz (Robles)', 'state' => 1, 'department_id' => 20],
            ['name' => 'La Peña', 'state' => 1, 'department_id' => 25],
            ['name' => 'La Pintada', 'state' => 1, 'department_id' => 5],
            ['name' => 'La Plata', 'state' => 1, 'department_id' => 41],
            ['name' => 'La Playa', 'state' => 1, 'department_id' => 54],
            ['name' => 'La Primavera', 'state' => 1, 'department_id' => 99],
            ['name' => 'La Salina', 'state' => 1, 'department_id' => 85],
            ['name' => 'La Sierra', 'state' => 1, 'department_id' => 19],
            ['name' => 'La Tebaida', 'state' => 1, 'department_id' => 63],
            ['name' => 'La Tola', 'state' => 1, 'department_id' => 52],
            ['name' => 'La Unión', 'state' => 1, 'department_id' => 5],
            ['name' => 'La Unión', 'state' => 1, 'department_id' => 52],
            ['name' => 'La Unión', 'state' => 1, 'department_id' => 70],
            ['name' => 'La Unión', 'state' => 1, 'department_id' => 76],
            ['name' => 'La Uvita', 'state' => 1, 'department_id' => 15],
            ['name' => 'La Vega', 'state' => 1, 'department_id' => 19],
            ['name' => 'La Vega', 'state' => 1, 'department_id' => 25],
            ['name' => 'La Victoria', 'state' => 1, 'department_id' => 15],
            ['name' => 'La Victoria', 'state' => 1, 'department_id' => 17],
            ['name' => 'La Victoria', 'state' => 1, 'department_id' => 76],
            ['name' => 'La Virginia', 'state' => 1, 'department_id' => 66],
            ['name' => 'Labateca', 'state' => 1, 'department_id' => 54],
            ['name' => 'Labranzagrande', 'state' => 1, 'department_id' => 15],
            ['name' => 'Landázuri', 'state' => 1, 'department_id' => 68],
            ['name' => 'Lebrija', 'state' => 1, 'department_id' => 68],
            ['name' => 'Leiva', 'state' => 1, 'department_id' => 52],
            ['name' => 'Lejanías', 'state' => 1, 'department_id' => 50],
            ['name' => 'Lenguazaque', 'state' => 1, 'department_id' => 25],
            ['name' => 'Leticia', 'state' => 1, 'department_id' => 91],
            ['name' => 'Liborina', 'state' => 1, 'department_id' => 5],
            ['name' => 'Linares', 'state' => 1, 'department_id' => 52],
            ['name' => 'Lloró', 'state' => 1, 'department_id' => 27],
            ['name' => 'Lorica', 'state' => 1, 'department_id' => 23],
            ['name' => 'Los Córdobas', 'state' => 1, 'department_id' => 23],
            ['name' => 'Los Palmitos', 'state' => 1, 'department_id' => 70],
            ['name' => 'Los Patios', 'state' => 1, 'department_id' => 54],
            ['name' => 'Los Santos', 'state' => 1, 'department_id' => 68],
            ['name' => 'Lourdes', 'state' => 1, 'department_id' => 54],
            ['name' => 'Luruaco', 'state' => 1, 'department_id' => 8],
            ['name' => 'Lérida', 'state' => 1, 'department_id' => 73],
            ['name' => 'Líbano', 'state' => 1, 'department_id' => 73],
            ['name' => 'López (Micay)', 'state' => 1, 'department_id' => 19],
            ['name' => 'Macanal', 'state' => 1, 'department_id' => 15],
            ['name' => 'Macaravita', 'state' => 1, 'department_id' => 68],
            ['name' => 'Maceo', 'state' => 1, 'department_id' => 5],
            ['name' => 'Machetá', 'state' => 1, 'department_id' => 25],
            ['name' => 'Madrid', 'state' => 1, 'department_id' => 25],
            ['name' => 'Magangué', 'state' => 1, 'department_id' => 13],
            ['name' => 'Magüi (Payán)', 'state' => 1, 'department_id' => 52],
            ['name' => 'Mahates', 'state' => 1, 'department_id' => 13],
            ['name' => 'Maicao', 'state' => 1, 'department_id' => 44],
            ['name' => 'Majagual', 'state' => 1, 'department_id' => 70],
            ['name' => 'Malambo', 'state' => 1, 'department_id' => 8],
            ['name' => 'Mallama (Piedrancha)', 'state' => 1, 'department_id' => 52],
            ['name' => 'Manatí', 'state' => 1, 'department_id' => 8],
            ['name' => 'Manaure', 'state' => 1, 'department_id' => 44],
            ['name' => 'Manaure Balcón del Cesar', 'state' => 1, 'department_id' => 20],
            ['name' => 'Manizales', 'state' => 1, 'department_id' => 17],
            ['name' => 'Manta', 'state' => 1, 'department_id' => 25],
            ['name' => 'Manzanares', 'state' => 1, 'department_id' => 17],
            ['name' => 'Maní', 'state' => 1, 'department_id' => 85],
            ['name' => 'Mapiripan', 'state' => 1, 'department_id' => 50],
            ['name' => 'Margarita', 'state' => 1, 'department_id' => 13],
            ['name' => 'Marinilla', 'state' => 1, 'department_id' => 5],
            ['name' => 'Maripí', 'state' => 1, 'department_id' => 15],
            ['name' => 'Mariquita', 'state' => 1, 'department_id' => 73],
            ['name' => 'Marmato', 'state' => 1, 'department_id' => 17],
            ['name' => 'Marquetalia', 'state' => 1, 'department_id' => 17],
            ['name' => 'Marsella', 'state' => 1, 'department_id' => 66],
            ['name' => 'Marulanda', 'state' => 1, 'department_id' => 17],
            ['name' => 'María la Baja', 'state' => 1, 'department_id' => 13],
            ['name' => 'Matanza', 'state' => 1, 'department_id' => 68],
            ['name' => 'Medellín', 'state' => 1, 'department_id' => 5],
            ['name' => 'Medina', 'state' => 1, 'department_id' => 25],
            ['name' => 'Medio Atrato', 'state' => 1, 'department_id' => 27],
            ['name' => 'Medio Baudó', 'state' => 1, 'department_id' => 27],
            ['name' => 'Medio San Juan (ANDAGOYA)', 'state' => 1, 'department_id' => 27],
            ['name' => 'Melgar', 'state' => 1, 'department_id' => 73],
            ['name' => 'Mercaderes', 'state' => 1, 'department_id' => 19],
            ['name' => 'Mesetas', 'state' => 1, 'department_id' => 50],
            ['name' => 'Milán', 'state' => 1, 'department_id' => 18],
            ['name' => 'Miraflores', 'state' => 1, 'department_id' => 15],
            ['name' => 'Miraflores', 'state' => 1, 'department_id' => 95],
            ['name' => 'Miranda', 'state' => 1, 'department_id' => 19],
            ['name' => 'Mistrató', 'state' => 1, 'department_id' => 66],
            ['name' => 'Mitú', 'state' => 1, 'department_id' => 97],
            ['name' => 'Mocoa', 'state' => 1, 'department_id' => 86],
            ['name' => 'Mogotes', 'state' => 1, 'department_id' => 68],
            ['name' => 'Molagavita', 'state' => 1, 'department_id' => 68],
            ['name' => 'Momil', 'state' => 1, 'department_id' => 23],
            ['name' => 'Mompós', 'state' => 1, 'department_id' => 13],
            ['name' => 'Mongua', 'state' => 1, 'department_id' => 15],
            ['name' => 'Monguí', 'state' => 1, 'department_id' => 15],
            ['name' => 'Moniquirá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Montebello', 'state' => 1, 'department_id' => 5],
            ['name' => 'Montecristo', 'state' => 1, 'department_id' => 13],
            ['name' => 'Montelíbano', 'state' => 1, 'department_id' => 23],
            ['name' => 'Montenegro', 'state' => 1, 'department_id' => 63],
            ['name' => 'Monteria', 'state' => 1, 'department_id' => 23],
            ['name' => 'Monterrey', 'state' => 1, 'department_id' => 85],
            ['name' => 'Morales', 'state' => 1, 'department_id' => 13],
            ['name' => 'Morales', 'state' => 1, 'department_id' => 19],
            ['name' => 'Morelia', 'state' => 1, 'department_id' => 18],
            ['name' => 'Morroa', 'state' => 1, 'department_id' => 70],
            ['name' => 'Mosquera', 'state' => 1, 'department_id' => 25],
            ['name' => 'Mosquera', 'state' => 1, 'department_id' => 52],
            ['name' => 'Motavita', 'state' => 1, 'department_id' => 15],
            ['name' => 'Moñitos', 'state' => 1, 'department_id' => 23],
            ['name' => 'Murillo', 'state' => 1, 'department_id' => 73],
            ['name' => 'Murindó', 'state' => 1, 'department_id' => 5],
            ['name' => 'Mutatá', 'state' => 1, 'department_id' => 5],
            ['name' => 'Mutiscua', 'state' => 1, 'department_id' => 54],
            ['name' => 'Muzo', 'state' => 1, 'department_id' => 15],
            ['name' => 'Málaga', 'state' => 1, 'department_id' => 68],
            ['name' => 'Nariño', 'state' => 1, 'department_id' => 5],
            ['name' => 'Nariño', 'state' => 1, 'department_id' => 25],
            ['name' => 'Nariño', 'state' => 1, 'department_id' => 52],
            ['name' => 'Natagaima', 'state' => 1, 'department_id' => 73],
            ['name' => 'Nechí', 'state' => 1, 'department_id' => 5],
            ['name' => 'Necoclí', 'state' => 1, 'department_id' => 5],
            ['name' => 'Neira', 'state' => 1, 'department_id' => 17],
            ['name' => 'Neiva', 'state' => 1, 'department_id' => 41],
            ['name' => 'Nemocón', 'state' => 1, 'department_id' => 25],
            ['name' => 'Nilo', 'state' => 1, 'department_id' => 25],
            ['name' => 'Nimaima', 'state' => 1, 'department_id' => 25],
            ['name' => 'Nobsa', 'state' => 1, 'department_id' => 15],
            ['name' => 'Nocaima', 'state' => 1, 'department_id' => 25],
            ['name' => 'Norcasia', 'state' => 1, 'department_id' => 17],
            ['name' => 'Norosí', 'state' => 1, 'department_id' => 13],
            ['name' => 'Novita', 'state' => 1, 'department_id' => 27],
            ['name' => 'Nueva Granada', 'state' => 1, 'department_id' => 47],
            ['name' => 'Nuevo Colón', 'state' => 1, 'department_id' => 15],
            ['name' => 'Nunchía', 'state' => 1, 'department_id' => 85],
            ['name' => 'Nuquí', 'state' => 1, 'department_id' => 27],
            ['name' => 'Nátaga', 'state' => 1, 'department_id' => 41],
            ['name' => 'Obando', 'state' => 1, 'department_id' => 76],
            ['name' => 'Ocamonte', 'state' => 1, 'department_id' => 68],
            ['name' => 'Ocaña', 'state' => 1, 'department_id' => 54],
            ['name' => 'Oiba', 'state' => 1, 'department_id' => 68],
            ['name' => 'Oicatá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Olaya', 'state' => 1, 'department_id' => 5],
            ['name' => 'Olaya Herrera', 'state' => 1, 'department_id' => 52],
            ['name' => 'Onzaga', 'state' => 1, 'department_id' => 68],
            ['name' => 'Oporapa', 'state' => 1, 'department_id' => 41],
            ['name' => 'Orito', 'state' => 1, 'department_id' => 86],
            ['name' => 'Orocué', 'state' => 1, 'department_id' => 85],
            ['name' => 'Ortega', 'state' => 1, 'department_id' => 73],
            ['name' => 'Ospina', 'state' => 1, 'department_id' => 52],
            ['name' => 'Otanche', 'state' => 1, 'department_id' => 15],
            ['name' => 'Ovejas', 'state' => 1, 'department_id' => 70],
            ['name' => 'Pachavita', 'state' => 1, 'department_id' => 15],
            ['name' => 'Pacho', 'state' => 1, 'department_id' => 25],
            ['name' => 'Padilla', 'state' => 1, 'department_id' => 19],
            ['name' => 'Paicol', 'state' => 1, 'department_id' => 41],
            ['name' => 'Pailitas', 'state' => 1, 'department_id' => 20],
            ['name' => 'Paime', 'state' => 1, 'department_id' => 25],
            ['name' => 'Paipa', 'state' => 1, 'department_id' => 15],
            ['name' => 'Pajarito', 'state' => 1, 'department_id' => 15],
            ['name' => 'Palermo', 'state' => 1, 'department_id' => 41],
            ['name' => 'Palestina', 'state' => 1, 'department_id' => 17],
            ['name' => 'Palestina', 'state' => 1, 'department_id' => 41],
            ['name' => 'Palmar', 'state' => 1, 'department_id' => 68],
            ['name' => 'Palmar de Varela', 'state' => 1, 'department_id' => 8],
            ['name' => 'Palmas del Socorro', 'state' => 1, 'department_id' => 68],
            ['name' => 'Palmira', 'state' => 1, 'department_id' => 76],
            ['name' => 'Palmito', 'state' => 1, 'department_id' => 70],
            ['name' => 'Palocabildo', 'state' => 1, 'department_id' => 73],
            ['name' => 'Pamplona', 'state' => 1, 'department_id' => 54],
            ['name' => 'Pamplonita', 'state' => 1, 'department_id' => 54],
            ['name' => 'Pandi', 'state' => 1, 'department_id' => 25],
            ['name' => 'Panqueba', 'state' => 1, 'department_id' => 15],
            ['name' => 'Paratebueno', 'state' => 1, 'department_id' => 25],
            ['name' => 'Pasca', 'state' => 1, 'department_id' => 25],
            ['name' => 'Patía (El Bordo)', 'state' => 1, 'department_id' => 19],
            ['name' => 'Pauna', 'state' => 1, 'department_id' => 15],
            ['name' => 'Paya', 'state' => 1, 'department_id' => 15],
            ['name' => 'Paz de Ariporo', 'state' => 1, 'department_id' => 85],
            ['name' => 'Paz de Río', 'state' => 1, 'department_id' => 15],
            ['name' => 'Pedraza', 'state' => 1, 'department_id' => 47],
            ['name' => 'Pelaya', 'state' => 1, 'department_id' => 20],
            ['name' => 'Pensilvania', 'state' => 1, 'department_id' => 17],
            ['name' => 'Peque', 'state' => 1, 'department_id' => 5],
            ['name' => 'Pereira', 'state' => 1, 'department_id' => 66],
            ['name' => 'Pesca', 'state' => 1, 'department_id' => 15],
            ['name' => 'Peñol', 'state' => 1, 'department_id' => 5],
            ['name' => 'Piamonte', 'state' => 1, 'department_id' => 19],
            ['name' => 'Pie de Cuesta', 'state' => 1, 'department_id' => 68],
            ['name' => 'Piedras', 'state' => 1, 'department_id' => 73],
            ['name' => 'Piendamó', 'state' => 1, 'department_id' => 19],
            ['name' => 'Pijao', 'state' => 1, 'department_id' => 63],
            ['name' => 'Pijiño', 'state' => 1, 'department_id' => 47],
            ['name' => 'Pinchote', 'state' => 1, 'department_id' => 68],
            ['name' => 'Pinillos', 'state' => 1, 'department_id' => 13],
            ['name' => 'Piojo', 'state' => 1, 'department_id' => 8],
            ['name' => 'Pisva', 'state' => 1, 'department_id' => 15],
            ['name' => 'Pital', 'state' => 1, 'department_id' => 41],
            ['name' => 'Pitalito', 'state' => 1, 'department_id' => 41],
            ['name' => 'Pivijay', 'state' => 1, 'department_id' => 47],
            ['name' => 'Planadas', 'state' => 1, 'department_id' => 73],
            ['name' => 'Planeta Rica', 'state' => 1, 'department_id' => 23],
            ['name' => 'Plato', 'state' => 1, 'department_id' => 47],
            ['name' => 'Policarpa', 'state' => 1, 'department_id' => 52],
            ['name' => 'Polonuevo', 'state' => 1, 'department_id' => 8],
            ['name' => 'Ponedera', 'state' => 1, 'department_id' => 8],
            ['name' => 'Popayán', 'state' => 1, 'department_id' => 19],
            ['name' => 'Pore', 'state' => 1, 'department_id' => 85],
            ['name' => 'Potosí', 'state' => 1, 'department_id' => 52],
            ['name' => 'Pradera', 'state' => 1, 'department_id' => 76],
            ['name' => 'Prado', 'state' => 1, 'department_id' => 73],
            ['name' => 'Providencia', 'state' => 1, 'department_id' => 52],
            ['name' => 'Providencia', 'state' => 1, 'department_id' => 88],
            ['name' => 'Pueblo Bello', 'state' => 1, 'department_id' => 20],
            ['name' => 'Pueblo Nuevo', 'state' => 1, 'department_id' => 23],
            ['name' => 'Pueblo Rico', 'state' => 1, 'department_id' => 66],
            ['name' => 'Pueblorrico', 'state' => 1, 'department_id' => 5],
            ['name' => 'Puebloviejo', 'state' => 1, 'department_id' => 47],
            ['name' => 'Puente Nacional', 'state' => 1, 'department_id' => 68],
            ['name' => 'Puerres', 'state' => 1, 'department_id' => 52],
            ['name' => 'Puerto Asís', 'state' => 1, 'department_id' => 86],
            ['name' => 'Puerto Berrío', 'state' => 1, 'department_id' => 5],
            ['name' => 'Puerto Boyacá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Puerto Caicedo', 'state' => 1, 'department_id' => 86],
            ['name' => 'Puerto Carreño', 'state' => 1, 'department_id' => 99],
            ['name' => 'Puerto Colombia', 'state' => 1, 'department_id' => 8],
            ['name' => 'Puerto Concordia', 'state' => 1, 'department_id' => 50],
            ['name' => 'Puerto Escondido', 'state' => 1, 'department_id' => 23],
            ['name' => 'Puerto Gaitán', 'state' => 1, 'department_id' => 50],
            ['name' => 'Puerto Guzmán', 'state' => 1, 'department_id' => 86],
            ['name' => 'Puerto Leguízamo', 'state' => 1, 'department_id' => 86],
            ['name' => 'Puerto Libertador', 'state' => 1, 'department_id' => 23],
            ['name' => 'Puerto Lleras', 'state' => 1, 'department_id' => 50],
            ['name' => 'Puerto López', 'state' => 1, 'department_id' => 50],
            ['name' => 'Puerto Nare', 'state' => 1, 'department_id' => 5],
            ['name' => 'Puerto Nariño', 'state' => 1, 'department_id' => 91],
            ['name' => 'Puerto Parra', 'state' => 1, 'department_id' => 68],
            ['name' => 'Puerto Rico', 'state' => 1, 'department_id' => 18],
            ['name' => 'Puerto Rico', 'state' => 1, 'department_id' => 50],
            ['name' => 'Puerto Rondón', 'state' => 1, 'department_id' => 81],
            ['name' => 'Puerto Salgar', 'state' => 1, 'department_id' => 25],
            ['name' => 'Puerto Santander', 'state' => 1, 'department_id' => 54],
            ['name' => 'Puerto Tejada', 'state' => 1, 'department_id' => 19],
            ['name' => 'Puerto Triunfo', 'state' => 1, 'department_id' => 5],
            ['name' => 'Puerto Wilches', 'state' => 1, 'department_id' => 68],
            ['name' => 'Pulí', 'state' => 1, 'department_id' => 25],
            ['name' => 'Pupiales', 'state' => 1, 'department_id' => 52],
            ['name' => 'Puracé (Coconuco)', 'state' => 1, 'department_id' => 19],
            ['name' => 'Purificación', 'state' => 1, 'department_id' => 73],
            ['name' => 'Purísima', 'state' => 1, 'department_id' => 23],
            ['name' => 'Pácora', 'state' => 1, 'department_id' => 17],
            ['name' => 'Páez', 'state' => 1, 'department_id' => 15],
            ['name' => 'Páez (Belalcazar)', 'state' => 1, 'department_id' => 19],
            ['name' => 'Páramo', 'state' => 1, 'department_id' => 68],
            ['name' => 'Quebradanegra', 'state' => 1, 'department_id' => 25],
            ['name' => 'Quetame', 'state' => 1, 'department_id' => 25],
            ['name' => 'Quibdó', 'state' => 1, 'department_id' => 27],
            ['name' => 'Quimbaya', 'state' => 1, 'department_id' => 63],
            ['name' => 'Quinchía', 'state' => 1, 'department_id' => 66],
            ['name' => 'Quipama', 'state' => 1, 'department_id' => 15],
            ['name' => 'Quipile', 'state' => 1, 'department_id' => 25],
            ['name' => 'Ragonvalia', 'state' => 1, 'department_id' => 54],
            ['name' => 'Ramiriquí', 'state' => 1, 'department_id' => 15],
            ['name' => 'Recetor', 'state' => 1, 'department_id' => 85],
            ['name' => 'Regidor', 'state' => 1, 'department_id' => 13],
            ['name' => 'Remedios', 'state' => 1, 'department_id' => 5],
            ['name' => 'Remolino', 'state' => 1, 'department_id' => 47],
            ['name' => 'Repelón', 'state' => 1, 'department_id' => 8],
            ['name' => 'Restrepo', 'state' => 1, 'department_id' => 50],
            ['name' => 'Restrepo', 'state' => 1, 'department_id' => 76],
            ['name' => 'Retiro', 'state' => 1, 'department_id' => 5],
            ['name' => 'Ricaurte', 'state' => 1, 'department_id' => 25],
            ['name' => 'Ricaurte', 'state' => 1, 'department_id' => 52],
            ['name' => 'Rio Negro', 'state' => 1, 'department_id' => 68],
            ['name' => 'Rioblanco', 'state' => 1, 'department_id' => 73],
            ['name' => 'Riofrío', 'state' => 1, 'department_id' => 76],
            ['name' => 'Riohacha', 'state' => 1, 'department_id' => 44],
            ['name' => 'Risaralda', 'state' => 1, 'department_id' => 17],
            ['name' => 'Rivera', 'state' => 1, 'department_id' => 41],
            ['name' => 'Roberto Payán (San José)', 'state' => 1, 'department_id' => 52],
            ['name' => 'Roldanillo', 'state' => 1, 'department_id' => 76],
            ['name' => 'Roncesvalles', 'state' => 1, 'department_id' => 73],
            ['name' => 'Rondón', 'state' => 1, 'department_id' => 15],
            ['name' => 'Rosas', 'state' => 1, 'department_id' => 19],
            ['name' => 'Rovira', 'state' => 1, 'department_id' => 73],
            ['name' => 'Ráquira', 'state' => 1, 'department_id' => 15],
            ['name' => 'Río Iró', 'state' => 1, 'department_id' => 27],
            ['name' => 'Río Quito', 'state' => 1, 'department_id' => 27],
            ['name' => 'Río Sucio', 'state' => 1, 'department_id' => 17],
            ['name' => 'Río Viejo', 'state' => 1, 'department_id' => 13],
            ['name' => 'Río de oro', 'state' => 1, 'department_id' => 20],
            ['name' => 'Ríonegro', 'state' => 1, 'department_id' => 5],
            ['name' => 'Ríosucio', 'state' => 1, 'department_id' => 27],
            ['name' => 'Sabana de Torres', 'state' => 1, 'department_id' => 68],
            ['name' => 'Sabanagrande', 'state' => 1, 'department_id' => 8],
            ['name' => 'Sabanalarga', 'state' => 1, 'department_id' => 5],
            ['name' => 'Sabanalarga', 'state' => 1, 'department_id' => 8],
            ['name' => 'Sabanalarga', 'state' => 1, 'department_id' => 85],
            ['name' => 'Sabanas de San Angel (SAN ANGEL)', 'state' => 1, 'department_id' => 47],
            ['name' => 'Sabaneta', 'state' => 1, 'department_id' => 5],
            ['name' => 'Saboyá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Sahagún', 'state' => 1, 'department_id' => 23],
            ['name' => 'Saladoblanco', 'state' => 1, 'department_id' => 41],
            ['name' => 'Salamina', 'state' => 1, 'department_id' => 17],
            ['name' => 'Salamina', 'state' => 1, 'department_id' => 47],
            ['name' => 'Salazar', 'state' => 1, 'department_id' => 54],
            ['name' => 'Saldaña', 'state' => 1, 'department_id' => 73],
            ['name' => 'Salento', 'state' => 1, 'department_id' => 63],
            ['name' => 'Salgar', 'state' => 1, 'department_id' => 5],
            ['name' => 'Samacá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Samaniego', 'state' => 1, 'department_id' => 52],
            ['name' => 'Samaná', 'state' => 1, 'department_id' => 17],
            ['name' => 'Sampués', 'state' => 1, 'department_id' => 70],
            ['name' => 'San Agustín', 'state' => 1, 'department_id' => 41],
            ['name' => 'San Alberto', 'state' => 1, 'department_id' => 20],
            ['name' => 'San Andrés', 'state' => 1, 'department_id' => 68],
            ['name' => 'San Andrés Sotavento', 'state' => 1, 'department_id' => 23],
            ['name' => 'San Andrés de Cuerquía', 'state' => 1, 'department_id' => 5],
            ['name' => 'San Antero', 'state' => 1, 'department_id' => 23],
            ['name' => 'San Antonio', 'state' => 1, 'department_id' => 73],
            ['name' => 'San Antonio de Tequendama', 'state' => 1, 'department_id' => 25],
            ['name' => 'San Benito', 'state' => 1, 'department_id' => 68],
            ['name' => 'San Benito Abad', 'state' => 1, 'department_id' => 70],
            ['name' => 'San Bernardo', 'state' => 1, 'department_id' => 25],
            ['name' => 'San Bernardo', 'state' => 1, 'department_id' => 52],
            ['name' => 'San Bernardo del Viento', 'state' => 1, 'department_id' => 23],
            ['name' => 'San Calixto', 'state' => 1, 'department_id' => 54],
            ['name' => 'San Carlos', 'state' => 1, 'department_id' => 5],
            ['name' => 'San Carlos', 'state' => 1, 'department_id' => 23],
            ['name' => 'San Carlos de Guaroa', 'state' => 1, 'department_id' => 50],
            ['name' => 'San Cayetano', 'state' => 1, 'department_id' => 25],
            ['name' => 'San Cayetano', 'state' => 1, 'department_id' => 54],
            ['name' => 'San Cristobal', 'state' => 1, 'department_id' => 13],
            ['name' => 'San Diego', 'state' => 1, 'department_id' => 20],
            ['name' => 'San Eduardo', 'state' => 1, 'department_id' => 15],
            ['name' => 'San Estanislao', 'state' => 1, 'department_id' => 13],
            ['name' => 'San Fernando', 'state' => 1, 'department_id' => 13],
            ['name' => 'San Francisco', 'state' => 1, 'department_id' => 5],
            ['name' => 'San Francisco', 'state' => 1, 'department_id' => 25],
            ['name' => 'San Francisco', 'state' => 1, 'department_id' => 86],
            ['name' => 'San Gíl', 'state' => 1, 'department_id' => 68],
            ['name' => 'San Jacinto', 'state' => 1, 'department_id' => 13],
            ['name' => 'San Jacinto del Cauca', 'state' => 1, 'department_id' => 13],
            ['name' => 'San Jerónimo', 'state' => 1, 'department_id' => 5],
            ['name' => 'San Joaquín', 'state' => 1, 'department_id' => 68],
            ['name' => 'San José', 'state' => 1, 'department_id' => 17],
            ['name' => 'San José de Miranda', 'state' => 1, 'department_id' => 68],
            ['name' => 'San José de Montaña', 'state' => 1, 'department_id' => 5],
            ['name' => 'San José de Pare', 'state' => 1, 'department_id' => 15],
            ['name' => 'San José de Uré', 'state' => 1, 'department_id' => 23],
            ['name' => 'San José del Fragua', 'state' => 1, 'department_id' => 18],
            ['name' => 'San José del Guaviare', 'state' => 1, 'department_id' => 95],
            ['name' => 'San José del Palmar', 'state' => 1, 'department_id' => 27],
            ['name' => 'San Juan de Arama', 'state' => 1, 'department_id' => 50],
            ['name' => 'San Juan de Betulia', 'state' => 1, 'department_id' => 70],
            ['name' => 'San Juan de Nepomuceno', 'state' => 1, 'department_id' => 13],
            ['name' => 'San Juan de Pasto', 'state' => 1, 'department_id' => 52],
            ['name' => 'San Juan de Río Seco', 'state' => 1, 'department_id' => 25],
            ['name' => 'San Juan de Urabá', 'state' => 1, 'department_id' => 5],
            ['name' => 'San Juan del Cesar', 'state' => 1, 'department_id' => 44],
            ['name' => 'San Juanito', 'state' => 1, 'department_id' => 50],
            ['name' => 'San Lorenzo', 'state' => 1, 'department_id' => 52],
            ['name' => 'San Luis', 'state' => 1, 'department_id' => 73],
            ['name' => 'San Luís', 'state' => 1, 'department_id' => 5],
            ['name' => 'San Luís de Gaceno', 'state' => 1, 'department_id' => 15],
            ['name' => 'San Luís de Palenque', 'state' => 1, 'department_id' => 85],
            ['name' => 'San Marcos', 'state' => 1, 'department_id' => 70],
            ['name' => 'San Martín', 'state' => 1, 'department_id' => 20],
            ['name' => 'San Martín', 'state' => 1, 'department_id' => 50],
            ['name' => 'San Martín de Loba', 'state' => 1, 'department_id' => 13],
            ['name' => 'San Mateo', 'state' => 1, 'department_id' => 15],
            ['name' => 'San Miguel', 'state' => 1, 'department_id' => 68],
            ['name' => 'San Miguel', 'state' => 1, 'department_id' => 86],
            ['name' => 'San Miguel de Sema', 'state' => 1, 'department_id' => 15],
            ['name' => 'San Onofre', 'state' => 1, 'department_id' => 70],
            ['name' => 'San Pablo', 'state' => 1, 'department_id' => 13],
            ['name' => 'San Pablo', 'state' => 1, 'department_id' => 52],
            ['name' => 'San Pablo de Borbur', 'state' => 1, 'department_id' => 15],
            ['name' => 'San Pedro', 'state' => 1, 'department_id' => 5],
            ['name' => 'San Pedro', 'state' => 1, 'department_id' => 70],
            ['name' => 'San Pedro', 'state' => 1, 'department_id' => 76],
            ['name' => 'San Pedro de Cartago', 'state' => 1, 'department_id' => 52],
            ['name' => 'San Pedro de Urabá', 'state' => 1, 'department_id' => 5],
            ['name' => 'San Pelayo', 'state' => 1, 'department_id' => 23],
            ['name' => 'San Rafael', 'state' => 1, 'department_id' => 5],
            ['name' => 'San Roque', 'state' => 1, 'department_id' => 5],
            ['name' => 'San Sebastián', 'state' => 1, 'department_id' => 19],
            ['name' => 'San Sebastián de Buenavista', 'state' => 1, 'department_id' => 47],
            ['name' => 'San Vicente', 'state' => 1, 'department_id' => 5],
            ['name' => 'San Vicente del Caguán', 'state' => 1, 'department_id' => 18],
            ['name' => 'San Vicente del Chucurí', 'state' => 1, 'department_id' => 68],
            ['name' => 'San Zenón', 'state' => 1, 'department_id' => 47],
            ['name' => 'Sandoná', 'state' => 1, 'department_id' => 52],
            ['name' => 'Santa Ana', 'state' => 1, 'department_id' => 47],
            ['name' => 'Santa Bárbara', 'state' => 1, 'department_id' => 5],
            ['name' => 'Santa Bárbara', 'state' => 1, 'department_id' => 68],
            ['name' => 'Santa Bárbara (Iscuandé)', 'state' => 1, 'department_id' => 52],
            ['name' => 'Santa Bárbara de Pinto', 'state' => 1, 'department_id' => 47],
            ['name' => 'Santa Catalina', 'state' => 1, 'department_id' => 13],
            ['name' => 'Santa Fé de Antioquia', 'state' => 1, 'department_id' => 5],
            ['name' => 'Santa Genoveva de Docorodó', 'state' => 1, 'department_id' => 27],
            ['name' => 'Santa Helena del Opón', 'state' => 1, 'department_id' => 68],
            ['name' => 'Santa Isabel', 'state' => 1, 'department_id' => 73],
            ['name' => 'Santa Lucía', 'state' => 1, 'department_id' => 8],
            ['name' => 'Santa Marta', 'state' => 1, 'department_id' => 47],
            ['name' => 'Santa María', 'state' => 1, 'department_id' => 15],
            ['name' => 'Santa María', 'state' => 1, 'department_id' => 41],
            ['name' => 'Santa Rosa', 'state' => 1, 'department_id' => 13],
            ['name' => 'Santa Rosa', 'state' => 1, 'department_id' => 19],
            ['name' => 'Santa Rosa de Cabal', 'state' => 1, 'department_id' => 66],
            ['name' => 'Santa Rosa de Osos', 'state' => 1, 'department_id' => 5],
            ['name' => 'Santa Rosa de Viterbo', 'state' => 1, 'department_id' => 15],
            ['name' => 'Santa Rosa del Sur', 'state' => 1, 'department_id' => 13],
            ['name' => 'Santa Rosalía', 'state' => 1, 'department_id' => 99],
            ['name' => 'Santa Sofía', 'state' => 1, 'department_id' => 15],
            ['name' => 'Santana', 'state' => 1, 'department_id' => 15],
            ['name' => 'Santander de Quilichao', 'state' => 1, 'department_id' => 19],
            ['name' => 'Santiago', 'state' => 1, 'department_id' => 54],
            ['name' => 'Santiago', 'state' => 1, 'department_id' => 86],
            ['name' => 'Santo Domingo', 'state' => 1, 'department_id' => 5],
            ['name' => 'Santo Tomás', 'state' => 1, 'department_id' => 8],
            ['name' => 'Santuario', 'state' => 1, 'department_id' => 5],
            ['name' => 'Santuario', 'state' => 1, 'department_id' => 66],
            ['name' => 'Sapuyes', 'state' => 1, 'department_id' => 52],
            ['name' => 'Saravena', 'state' => 1, 'department_id' => 81],
            ['name' => 'Sardinata', 'state' => 1, 'department_id' => 54],
            ['name' => 'Sasaima', 'state' => 1, 'department_id' => 25],
            ['name' => 'Sativanorte', 'state' => 1, 'department_id' => 15],
            ['name' => 'Sativasur', 'state' => 1, 'department_id' => 15],
            ['name' => 'Segovia', 'state' => 1, 'department_id' => 5],
            ['name' => 'Sesquilé', 'state' => 1, 'department_id' => 25],
            ['name' => 'Sevilla', 'state' => 1, 'department_id' => 76],
            ['name' => 'Siachoque', 'state' => 1, 'department_id' => 15],
            ['name' => 'Sibaté', 'state' => 1, 'department_id' => 25],
            ['name' => 'Sibundoy', 'state' => 1, 'department_id' => 86],
            ['name' => 'Silos', 'state' => 1, 'department_id' => 54],
            ['name' => 'Silvania', 'state' => 1, 'department_id' => 25],
            ['name' => 'Silvia', 'state' => 1, 'department_id' => 19],
            ['name' => 'Simacota', 'state' => 1, 'department_id' => 68],
            ['name' => 'Simijaca', 'state' => 1, 'department_id' => 25],
            ['name' => 'Simití', 'state' => 1, 'department_id' => 13],
            ['name' => 'Sincelejo', 'state' => 1, 'department_id' => 70],
            ['name' => 'Sincé', 'state' => 1, 'department_id' => 70],
            ['name' => 'Sipí', 'state' => 1, 'department_id' => 27],
            ['name' => 'Sitionuevo', 'state' => 1, 'department_id' => 47],
            ['name' => 'Soacha', 'state' => 1, 'department_id' => 25],
            ['name' => 'Soatá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Socha', 'state' => 1, 'department_id' => 15],
            ['name' => 'Socorro', 'state' => 1, 'department_id' => 68],
            ['name' => 'Socotá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Sogamoso', 'state' => 1, 'department_id' => 15],
            ['name' => 'Solano', 'state' => 1, 'department_id' => 18],
            ['name' => 'Soledad', 'state' => 1, 'department_id' => 8],
            ['name' => 'Solita', 'state' => 1, 'department_id' => 18],
            ['name' => 'Somondoco', 'state' => 1, 'department_id' => 15],
            ['name' => 'Sonsón', 'state' => 1, 'department_id' => 5],
            ['name' => 'Sopetrán', 'state' => 1, 'department_id' => 5],
            ['name' => 'Soplaviento', 'state' => 1, 'department_id' => 13],
            ['name' => 'Sopó', 'state' => 1, 'department_id' => 25],
            ['name' => 'Sora', 'state' => 1, 'department_id' => 15],
            ['name' => 'Soracá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Sotaquirá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Sotara (Paispamba)', 'state' => 1, 'department_id' => 19],
            ['name' => 'Sotomayor (Los Andes)', 'state' => 1, 'department_id' => 52],
            ['name' => 'Suaita', 'state' => 1, 'department_id' => 68],
            ['name' => 'Suan', 'state' => 1, 'department_id' => 8],
            ['name' => 'Suaza', 'state' => 1, 'department_id' => 41],
            ['name' => 'Subachoque', 'state' => 1, 'department_id' => 25],
            ['name' => 'Sucre', 'state' => 1, 'department_id' => 19],
            ['name' => 'Sucre', 'state' => 1, 'department_id' => 68],
            ['name' => 'Sucre', 'state' => 1, 'department_id' => 70],
            ['name' => 'Suesca', 'state' => 1, 'department_id' => 25],
            ['name' => 'Supatá', 'state' => 1, 'department_id' => 25],
            ['name' => 'Supía', 'state' => 1, 'department_id' => 17],
            ['name' => 'Suratá', 'state' => 1, 'department_id' => 68],
            ['name' => 'Susa', 'state' => 1, 'department_id' => 25],
            ['name' => 'Susacón', 'state' => 1, 'department_id' => 15],
            ['name' => 'Sutamarchán', 'state' => 1, 'department_id' => 15],
            ['name' => 'Sutatausa', 'state' => 1, 'department_id' => 25],
            ['name' => 'Sutatenza', 'state' => 1, 'department_id' => 15],
            ['name' => 'Suárez', 'state' => 1, 'department_id' => 19],
            ['name' => 'Suárez', 'state' => 1, 'department_id' => 73],
            ['name' => 'Sácama', 'state' => 1, 'department_id' => 85],
            ['name' => 'Sáchica', 'state' => 1, 'department_id' => 15],
            ['name' => 'Tabio', 'state' => 1, 'department_id' => 25],
            ['name' => 'Tadó', 'state' => 1, 'department_id' => 27],
            ['name' => 'Talaigua Nuevo', 'state' => 1, 'department_id' => 13],
            ['name' => 'Tamalameque', 'state' => 1, 'department_id' => 20],
            ['name' => 'Tame', 'state' => 1, 'department_id' => 81],
            ['name' => 'Taminango', 'state' => 1, 'department_id' => 52],
            ['name' => 'Tangua', 'state' => 1, 'department_id' => 52],
            ['name' => 'Taraira', 'state' => 1, 'department_id' => 97],
            ['name' => 'Tarazá', 'state' => 1, 'department_id' => 5],
            ['name' => 'Tarqui', 'state' => 1, 'department_id' => 41],
            ['name' => 'Tarso', 'state' => 1, 'department_id' => 5],
            ['name' => 'Tasco', 'state' => 1, 'department_id' => 15],
            ['name' => 'Tauramena', 'state' => 1, 'department_id' => 85],
            ['name' => 'Tausa', 'state' => 1, 'department_id' => 25],
            ['name' => 'Tello', 'state' => 1, 'department_id' => 41],
            ['name' => 'Tena', 'state' => 1, 'department_id' => 25],
            ['name' => 'Tenerife', 'state' => 1, 'department_id' => 47],
            ['name' => 'Tenjo', 'state' => 1, 'department_id' => 25],
            ['name' => 'Tenza', 'state' => 1, 'department_id' => 15],
            ['name' => 'Teorama', 'state' => 1, 'department_id' => 54],
            ['name' => 'Teruel', 'state' => 1, 'department_id' => 41],
            ['name' => 'Tesalia', 'state' => 1, 'department_id' => 41],
            ['name' => 'Tibacuy', 'state' => 1, 'department_id' => 25],
            ['name' => 'Tibaná', 'state' => 1, 'department_id' => 15],
            ['name' => 'Tibasosa', 'state' => 1, 'department_id' => 15],
            ['name' => 'Tibirita', 'state' => 1, 'department_id' => 25],
            ['name' => 'Tibú', 'state' => 1, 'department_id' => 54],
            ['name' => 'Tierralta', 'state' => 1, 'department_id' => 23],
            ['name' => 'Timaná', 'state' => 1, 'department_id' => 41],
            ['name' => 'Timbiquí', 'state' => 1, 'department_id' => 19],
            ['name' => 'Timbío', 'state' => 1, 'department_id' => 19],
            ['name' => 'Tinjacá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Tipacoque', 'state' => 1, 'department_id' => 15],
            ['name' => 'Tiquisio (Puerto Rico)', 'state' => 1, 'department_id' => 13],
            ['name' => 'Titiribí', 'state' => 1, 'department_id' => 5],
            ['name' => 'Toca', 'state' => 1, 'department_id' => 15],
            ['name' => 'Tocaima', 'state' => 1, 'department_id' => 25],
            ['name' => 'Tocancipá', 'state' => 1, 'department_id' => 25],
            ['name' => 'Toguí', 'state' => 1, 'department_id' => 15],
            ['name' => 'Toledo', 'state' => 1, 'department_id' => 5],
            ['name' => 'Toledo', 'state' => 1, 'department_id' => 54],
            ['name' => 'Tolú', 'state' => 1, 'department_id' => 70],
            ['name' => 'Tolú Viejo', 'state' => 1, 'department_id' => 70],
            ['name' => 'Tona', 'state' => 1, 'department_id' => 68],
            ['name' => 'Topagá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Topaipí', 'state' => 1, 'department_id' => 25],
            ['name' => 'Toribío', 'state' => 1, 'department_id' => 19],
            ['name' => 'Toro', 'state' => 1, 'department_id' => 76],
            ['name' => 'Tota', 'state' => 1, 'department_id' => 15],
            ['name' => 'Totoró', 'state' => 1, 'department_id' => 19],
            ['name' => 'Trinidad', 'state' => 1, 'department_id' => 85],
            ['name' => 'Trujillo', 'state' => 1, 'department_id' => 76],
            ['name' => 'Tubará', 'state' => 1, 'department_id' => 8],
            ['name' => 'Tuchín', 'state' => 1, 'department_id' => 23],
            ['name' => 'Tulúa', 'state' => 1, 'department_id' => 76],
            ['name' => 'Tumaco', 'state' => 1, 'department_id' => 52],
            ['name' => 'Tunja', 'state' => 1, 'department_id' => 15],
            ['name' => 'Tunungua', 'state' => 1, 'department_id' => 15],
            ['name' => 'Turbaco', 'state' => 1, 'department_id' => 13],
            ['name' => 'Turbaná', 'state' => 1, 'department_id' => 13],
            ['name' => 'Turbo', 'state' => 1, 'department_id' => 5],
            ['name' => 'Turmequé', 'state' => 1, 'department_id' => 15],
            ['name' => 'Tuta', 'state' => 1, 'department_id' => 15],
            ['name' => 'Tutasá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Támara', 'state' => 1, 'department_id' => 85],
            ['name' => 'Támesis', 'state' => 1, 'department_id' => 5],
            ['name' => 'Túquerres', 'state' => 1, 'department_id' => 52],
            ['name' => 'Ubalá', 'state' => 1, 'department_id' => 25],
            ['name' => 'Ubaque', 'state' => 1, 'department_id' => 25],
            ['name' => 'Ubaté', 'state' => 1, 'department_id' => 25],
            ['name' => 'Ulloa', 'state' => 1, 'department_id' => 76],
            ['name' => 'Une', 'state' => 1, 'department_id' => 25],
            ['name' => 'Unguía', 'state' => 1, 'department_id' => 27],
            ['name' => 'Unión Panamericana (ÁNIMAS)', 'state' => 1, 'department_id' => 27],
            ['name' => 'Uramita', 'state' => 1, 'department_id' => 5],
            ['name' => 'Uribe', 'state' => 1, 'department_id' => 50],
            ['name' => 'Uribia', 'state' => 1, 'department_id' => 44],
            ['name' => 'Urrao', 'state' => 1, 'department_id' => 5],
            ['name' => 'Urumita', 'state' => 1, 'department_id' => 44],
            ['name' => 'Usiacuri', 'state' => 1, 'department_id' => 8],
            ['name' => 'Valdivia', 'state' => 1, 'department_id' => 5],
            ['name' => 'Valencia', 'state' => 1, 'department_id' => 23],
            ['name' => 'Valle de San José', 'state' => 1, 'department_id' => 68],
            ['name' => 'Valle de San Juan', 'state' => 1, 'department_id' => 73],
            ['name' => 'Valle del Guamuez', 'state' => 1, 'department_id' => 86],
            ['name' => 'Valledupar', 'state' => 1, 'department_id' => 20],
            ['name' => 'Valparaiso', 'state' => 1, 'department_id' => 5],
            ['name' => 'Valparaiso', 'state' => 1, 'department_id' => 18],
            ['name' => 'Vegachí', 'state' => 1, 'department_id' => 5],
            ['name' => 'Venadillo', 'state' => 1, 'department_id' => 73],
            ['name' => 'Venecia', 'state' => 1, 'department_id' => 5],
            ['name' => 'Venecia (Ospina Pérez)', 'state' => 1, 'department_id' => 25],
            ['name' => 'Ventaquemada', 'state' => 1, 'department_id' => 15],
            ['name' => 'Vergara', 'state' => 1, 'department_id' => 25],
            ['name' => 'Versalles', 'state' => 1, 'department_id' => 76],
            ['name' => 'Vetas', 'state' => 1, 'department_id' => 68],
            ['name' => 'Viani', 'state' => 1, 'department_id' => 25],
            ['name' => 'Vigía del Fuerte', 'state' => 1, 'department_id' => 5],
            ['name' => 'Vijes', 'state' => 1, 'department_id' => 76],
            ['name' => 'Villa Caro', 'state' => 1, 'department_id' => 54],
            ['name' => 'Villa Rica', 'state' => 1, 'department_id' => 19],
            ['name' => 'Villa de Leiva', 'state' => 1, 'department_id' => 15],
            ['name' => 'Villa del Rosario', 'state' => 1, 'department_id' => 54],
            ['name' => 'Villagarzón', 'state' => 1, 'department_id' => 86],
            ['name' => 'Villagómez', 'state' => 1, 'department_id' => 25],
            ['name' => 'Villahermosa', 'state' => 1, 'department_id' => 73],
            ['name' => 'Villamaría', 'state' => 1, 'department_id' => 17],
            ['name' => 'Villanueva', 'state' => 1, 'department_id' => 13],
            ['name' => 'Villanueva', 'state' => 1, 'department_id' => 44],
            ['name' => 'Villanueva', 'state' => 1, 'department_id' => 68],
            ['name' => 'Villanueva', 'state' => 1, 'department_id' => 85],
            ['name' => 'Villapinzón', 'state' => 1, 'department_id' => 25],
            ['name' => 'Villarrica', 'state' => 1, 'department_id' => 73],
            ['name' => 'Villavicencio', 'state' => 1, 'department_id' => 50],
            ['name' => 'Villavieja', 'state' => 1, 'department_id' => 41],
            ['name' => 'Villeta', 'state' => 1, 'department_id' => 25],
            ['name' => 'Viotá', 'state' => 1, 'department_id' => 25],
            ['name' => 'Viracachá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Vista Hermosa', 'state' => 1, 'department_id' => 50],
            ['name' => 'Viterbo', 'state' => 1, 'department_id' => 17],
            ['name' => 'Vélez', 'state' => 1, 'department_id' => 68],
            ['name' => 'Yacopí', 'state' => 1, 'department_id' => 25],
            ['name' => 'Yacuanquer', 'state' => 1, 'department_id' => 52],
            ['name' => 'Yaguará', 'state' => 1, 'department_id' => 41],
            ['name' => 'Yalí', 'state' => 1, 'department_id' => 5],
            ['name' => 'Yarumal', 'state' => 1, 'department_id' => 5],
            ['name' => 'Yolombó', 'state' => 1, 'department_id' => 5],
            ['name' => 'Yondó (Casabe)', 'state' => 1, 'department_id' => 5],
            ['name' => 'Yopal', 'state' => 1, 'department_id' => 85],
            ['name' => 'Yotoco', 'state' => 1, 'department_id' => 76],
            ['name' => 'Yumbo', 'state' => 1, 'department_id' => 76],
            ['name' => 'Zambrano', 'state' => 1, 'department_id' => 13],
            ['name' => 'Zapatoca', 'state' => 1, 'department_id' => 68],
            ['name' => 'Zapayán (PUNTA DE PIEDRAS)', 'state' => 1, 'department_id' => 47],
            ['name' => 'Zaragoza', 'state' => 1, 'department_id' => 5],
            ['name' => 'Zarzal', 'state' => 1, 'department_id' => 76],
            ['name' => 'Zetaquirá', 'state' => 1, 'department_id' => 15],
            ['name' => 'Zipacón', 'state' => 1, 'department_id' => 25],
            ['name' => 'Zipaquirá', 'state' => 1, 'department_id' => 25],
            ['name' => 'Zona Bananera (PRADO - SEVILLA)', 'state' => 1, 'department_id' => 47],
            ['name' => 'Ábrego', 'state' => 1, 'department_id' => 54],
            ['name' => 'Íquira', 'state' => 1, 'department_id' => 41],
            ['name' => 'Úmbita', 'state' => 1, 'department_id' => 15],
            ['name' => 'Útica', 'state' => 1, 'department_id' => 25],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('towns');
    }
}
